## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://118.25.108.65:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: Mysql@123456
    driver-class-name: com.mysql.cj.jdbc.Driver