## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://118.25.108.65:3306/production?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver