spring:
  application:
    name: rabbitmq-server
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true  #生产者开启confirm，确认消息是否到达broker，只要正确到达exchange即可
    publisher-returns: true  #确认消息是否正确到达queue
    template:
      mandatory: true  #投递失败强制将消息返回给生产者

