## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.33.120:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Mysql@123456
    driver-class-name: com.mysql.jdbc.Driver