#端口
server:
  port: 8081

spring:
  profiles:
    active: test
  ## 配置正式和测试库，分别是production/test
  #  profiles:
  #    active: @filters.env@
#  jpa:
#    show-sql: true
  activemq:
    broker-url:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: springboot-group
      enable-auto-commit: true
    producer:
      batch-size: 65536
      buffer-memory: 524288
#  # 邮件
#  mail:
#    host: smtp.163.com
#    username: XXXX@163.com
#    password:
#    default-encoding: UTF-8

## kafka主题
kafka:
  topic: test
  SMS-Topic: SMS-Topic

# 日志
log:
  level: INFO

# mybatis 控制台打印SQL日志
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: ount=countSql

# 七牛 域名过期
#qiniu:
#  public:
#    bucket: test-web
#    domain: p1gixpzpk.bkt.clouddn.com
