spring:
  datasource:
    ds-0:
      hikari:
        jdbc-url: jdbc:mysql://172.16.100.67:3306/sharding-test
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: 123456
        minimum-idle: 10
        maximum-pool-size: 200
        pool-name: DS0HikariCP
        connection-timeout: 30000
        connection-test-query: select 1
        max-lifetime: 600000
        idle-timeout: 120000
        data-source-properties: {cachePrepStmts: true, prepStmtCacheSize: 250, prepStmtCacheSqlLimit: 2048, useServerPrepStmts: true}
    ds-1:
      hikari:
        jdbc-url: jdbc:mysql://192.168.33.120:3306/sharding-test
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: Mysql@123456
        minimum-idle: 10
        maximum-pool-size: 200
        pool-name: DS1HikariCP
        connection-timeout: 30000
        connection-test-query: select 1
        max-lifetime: 600000
        idle-timeout: 120000
        data-source-properties: {cachePrepStmts: true, prepStmtCacheSize: 250, prepStmtCacheSqlLimit: 2048, useServerPrepStmts: true}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      #需要关闭ddl语句，在多表中不适用
      ddl-auto: none

